### ISSUE TITLE
Bad LOA handling

### ISSUE THREAD

**Issue by Peder2911** [prio-data/views_queryset_manager#15]
LOAs are currently handled very badly througout the system, being defined both
at the base_data_retriever level and at the queryset_manager level. The QSM
does it worst, by making the possible values of the LOA model an enum, which
completely calcifies the configuration of these values

I need to figure out a much better way to handle this than the current setup.

**Comment by Peder2911** [comment]
Also, posted querysets with LOAs that are not valid for the enum currently
makes the service return a 500, which is not ok. This should be a quick fix,
though.

**Comment by Peder2911** [comment]
Fixed by ba8c3af

**Comment by hhegre** [comment]
All combinations of actor, country, and priogrid data should work, including any temporal resolution (month, year, permanent/none) for each of them. Combinations means any pair or set of three or four or higher of levels. The output of this can be in any of these levels. 

Mihai and Jim can supply test queries.

**Comment by Peder2911** [comment]
I am pretty sure that I know how to handle this now. I'll set up a service that lets users define LOAs in terms of a table, time-column, unit-column combination, and then let the other services get this information from there.

**Comment by Peder2911** [comment]
This is now partially handled via https://github.com/prio-data/views_queryset_manager/commit/f3ee4c014efa79b56fb63d9d8053269631891ce9. Working on the data retriever fix at https://github.com/prio-data/base_data_retriever/tree/feature/bdr-revamp.

**Comment by Peder2911** [comment]
I am on the home stretch with regards to this issue, will finalize tomorrow.

**Comment by Peder2911** [comment]
Solved in https://github.com/prio-data/base_data_retriever/commit/a99b32014c2526b3f9670e4df8d0b73961e3e203 -> https://github.com/prio-data/views3/commit/5a181170debcabfdf683c8151f35ac98aae1627e.
